### ISSUE TITLE
Redundans hanging on scaffold.longread stage

### ISSUE THREAD

**Issue by ens-LCampbell** [Gabaldonlab/redundans#60] opened 2019-02-21 12:40 UTC
Essentially, from what I can see... redundans has stalled completely once it reaches the stage of scaffolding. The files produced up to that point: 

lrwxrwxrwx 1 lcampbell ensembl        243 Feb 21 11:56 contigs.fa -> some/path
-rw-r--r-- 1 lcampbell ensembl  125230004 Feb 21 11:56 contigs.fa.bck
-rw-r--r-- 1 lcampbell ensembl      52500 Feb 21 11:56 contigs.fa.des
lrwxrwxrwx 1 lcampbell ensembl        245 Feb 21 11:56 contigs.fa.fai -> some/path/
-rw-r--r-- 1 lcampbell ensembl        501 Feb 21 11:56 contigs.fa.prj
-rw-r--r-- 1 lcampbell ensembl      17504 Feb 21 11:56 contigs.fa.sds
-rw-r--r-- 1 lcampbell ensembl      17504 Feb 21 11:56 contigs.fa.ssp
-rw-r--r-- 1 lcampbell ensembl  550592660 Feb 21 11:56 contigs.fa.suf
-rw-r--r-- 1 lcampbell ensembl  728802868 Feb 21 11:56 contigs.fa.tis
-rw-r--r-- 1 lcampbell ensembl  626149432 Feb 21 11:56 contigs.reduced.fa
-rw-r--r-- 1 lcampbell ensembl  460774324 Feb 21 11:56 contigs.reduced.fa.bck
-rw-r--r-- 1 lcampbell ensembl      30048 Feb 21 11:56 contigs.reduced.fa.des
-rw-r--r-- 1 lcampbell ensembl     163532 Feb 21 11:56 contigs.reduced.fa.fai
-rw-r--r-- 1 lcampbell ensembl      78832 Feb 21 11:56 contigs.reduced.fa.hetero.tsv
-rw-r--r-- 1 lcampbell ensembl        477 Feb 21 11:56 contigs.reduced.fa.prj
-rw-r--r-- 1 lcampbell ensembl      10020 Feb 21 11:56 contigs.reduced.fa.sds
-rw-r--r-- 1 lcampbell ensembl      10020 Feb 21 11:56 contigs.reduced.fa.ssp
-rw-r--r-- 1 lcampbell ensembl 2504457504 Feb 21 11:56 contigs.reduced.fa.suf
-rw-r--r-- 1 lcampbell ensembl  626116881 Feb 21 11:56 contigs.reduced.fa.tis
-rw-r--r-- 1 lcampbell ensembl       3467 Feb 21 11:56 contigs.reduced_N50.txt
-rw-r--r-- 1 lcampbell ensembl          0 Feb 21 11:56 scaffolds.longreads.1.fa

The most recent file produced is scaffolds.longreads.1.fa. However it is 100% empty and hasn't changed so in 2 days. Running on 36 cpu and 30Gb RAM. 
Note I've ran Redundans many times successfully, on the same set of input long reads essentially. This time my assembly was changed from the last run (to remove contaminants). Previous run took <24hrs. 

The only thing I can think of is the read headers now might be an issue. As an example Some reads have a header like so:
>m54053_170823_104252/4784600/0_20730 kraken:taxid|7038 id=90 clr=0,20474

Others have simply like so:
>m54053_170823_104252/4784600/0_20730

I have since the last successful run of Redundans, filtered assembly reads prior to assembly using Kraken then reassembled and now trying to haplo collapse. Might this affect redundans at all when it comes to scaffolding ? Or does it even consider headers following the first whitespace ? The Long reads are ~30Gb. 

If I resume a run nothing happens it just says:
[Thu Feb 21 11:58:37 2019] Resuming previous run from ./Outdir_Redundans 

The redundans test dataset completes fine obviously. And as I say other runs I've done in the past caused no issues at all, finishing in 24hrs roughly.

Any help much appreciated. 

Thank you.
Lahcen

**Comment by lpryszcz** [comment] 2019-05-06 15:39
Dear Lahcen, I'm afraid I have no idea. Could you please send me some sample data so I can reproduce the issue?

**Comment by astaroph** [comment] 2019-06-20 18:49
I think I have the same problem, actually. I thought at first it was just because its a large-ish (1Gb) polyploid plant genome, but I'll try using different versions of these read files (as I've de-duplicated and whitespace stripped both the nanopore and illumina reads) and see what happens.
I have 3 different assemblies, made by canu, miniasm and masurca, all subsequently processed differently that are having this same issue, so perhaps it is either the long or short reads or the structure of the genome itself, as these are the constants between those assemblies?

Here is output from the canu assembly below, started on the 14th and still running without output today:
Many Thanks!

lrwxrwxrwx  1 astaroph pierce_lab        124 Jun 14 08:56 contigs.fa -> path
-rw-rw----+ 1 astaroph pierce_lab  192338868 Jun 14 08:57 contigs.fa.bck
-rw-rw----+ 1 astaroph pierce_lab     292236 Jun 14 08:56 contigs.fa.des
lrwxrwxrwx  1 astaroph pierce_lab        128 Jun 14 08:56 contigs.fa.fai -> path
-rw-rw----+ 1 astaroph pierce_lab        504 Jun 14 08:57 contigs.fa.prj
-rw-rw----+ 1 astaroph pierce_lab      97416 Jun 14 08:56 contigs.fa.sds
-rw-rw----+ 1 astaroph pierce_lab      97416 Jun 14 08:56 contigs.fa.ssp
-rw-rw----+ 1 astaroph pierce_lab  852928288 Jun 14 08:57 contigs.fa.suf
-rw-rw----+ 1 astaroph pierce_lab 1137405355 Jun 14 08:56 contigs.fa.tis
-rw-rw----+ 1 astaroph pierce_lab  951756508 Jun 14 14:45 contigs.reduced.fa
-rw-rw----+ 1 astaroph pierce_lab   47739282 Jun 14 14:46 contigs.reduced.fa.0.05
-rw-rw----+ 1 astaroph pierce_lab     987965 Jun 14 14:46 contigs.reduced.fa.fai
-rw-rw----+ 1 astaroph pierce_lab     353215 Jun 14 14:45 contigs.reduced.fa.hetero.tsv
-rw-rw----+ 1 astaroph pierce_lab     106988 Jun 14 14:42 contigs.reduced.fa.hist.png
lrwxrwxrwx  1 astaroph pierce_lab         18 Jun 14 14:46 scaffolds.fa -> contigs.reduced.fa
-rw-rw----+ 1 astaroph pierce_lab  460774324 Jun 14 14:54 scaffolds.fa.bck
-rw-rw----+ 1 astaroph pierce_lab     190644 Jun 14 14:47 scaffolds.fa.des
lrwxrwxrwx  1 astaroph pierce_lab         22 Jun 14 14:46 scaffolds.fa.fai -> contigs.reduced.fa.fai
-rw-rw----+ 1 astaroph pierce_lab        479 Jun 14 14:54 scaffolds.fa.prj
-rw-rw----+ 1 astaroph pierce_lab      63552 Jun 14 14:47 scaffolds.fa.sds
-rw-rw----+ 1 astaroph pierce_lab      63552 Jun 14 14:47 scaffolds.fa.ssp
-rw-rw----+ 1 astaroph pierce_lab 3806121696 Jun 14 14:54 scaffolds.fa.suf
-rw-rw----+ 1 astaroph pierce_lab  951549978 Jun 14 14:47 scaffolds.fa.tis
-rw-rw----+ 1 astaroph pierce_lab          0 Jun 14 14:46 scaffolds.longreads.1.fa

**Comment by ksawatzki** [comment] 2019-09-27 18:16
I'm having the same issue - hanging on "Scaffolding with long reads..." iteration 1. 
This is using ONT reads on a mammalian Masurca assembly with ~6k contigs. Any movement on this?

**Comment by ksawatzki** [comment] 2019-10-01 16:24
If anyone else gets hung up at this step, I've been able to successfully run the output of Redundans with reduction only (contigs.reduced.fa) with standalone pyScaf using the same input and options, then running gap closing with Redundans again. It's not ideal, but I believe it's what the pipeline was doing anyway.

**Comment by astaroph** [comment] 2019-10-01 16:47
Update, after letting the job just continue running, 2 of my currently running 4 assemblies (they are all the same species and input files, just different assembly pipelines and sizes) eventually completed. Around every 7 days, they would output one of the "scaffolds.longreads.X.fa" files and then start on the next, and after about 3-5 rounds of this, they would eventually finish, apparently normally. 

These were runs that were resuming from right before this longreads.scaffold stage, and the only hint that something was behaving abnormally was the following error output right before hanging on the first scaffold stage:
ERROR: could not find an header containing scaffold8047|size41153 at line number 1. Exit...

Nonetheless, the whole job eventually completed for the first two assemblies I'm running, improving the stats impressively, so I've just given my remaining 2 jobs a healthy 60 days of runtime and will let them play out.

Memory limitations may possibly have an impact at this step, although I've observed nothing conclusive: The first time I ran my 2 largest assemblies, they took over a week to output the first scaffolds.longreads.1.fa, using 50Gb RAM on 20 cores, whereas this time I bumped up the RAM to 200Gb with the same number of cores and they output the first file in around 4 days.

**Comment by matryoskina** [comment] 2020-05-01 13:50
Hi all, I also had the same problem, and finally I realised that for some reasons LAST run with only 1 CPU at this step! No matter how much CPU you set, it will only use 1. Forget to have an output. I'm running this step outside of the pipeline, using pyScaf alone, as @ksawatzki suggested. 
Maybe @lpryszcz something changed with new releases?

**Comment by lpryszcz** [comment] 2020-09-29 17:58
Hi @matryoskina , thanks for the hint! I've been just discussing today with another user problems related to long-read scaffolding. Frankly long-read scaffolder [pyScaf](https://github.com/lpryszcz/pyScaf) isn't optimal solution, especially for larger genomes. 

@astaroph @ksawatzki @ens-LCampbell I have two ideas to try - if you wish to join the chat & possibly test it, please drop me a message via [our mailing list](https://groups.google.com/g/redundans). 
Apart from that, I'd like to sit down and improve Redundans, starting from porting it to Python3. This can be a community project (possibly also publication) so just let me know your ideas and what needs to be done :) 
Cheers,

**Comment by astaroph** [comment] 2020-11-04 15:03
@lpryszcz @matryoskina 
Update on my end, I also noticed the issue appeared to be with LAST taking a long time to do the alignments, so I made an altered version of redundans.py that invokes minimap2 instead of LAST, and it appears to run OK. That being said, I haven't optimized the alignment parameters of that step yet, so its just a basic minimap2 long read alignment (the nanopore profile in my case), but it finishes successfully, and appears to improve my assembly.

CORRECTION:
It was the pyscaf.py file I edited to replace LAST with minimap2, not redundans.py

**Comment by lpryszcz** [comment] 2020-11-13 09:13
> It was the pyscaf.py file I edited to replace LAST with minimap2, not redundans.py  

thanks for the update!

**Closed as completed** 2021-11-15 04:00 UTC
Labels: enhancement
